# Generated by stage-hosttools-atlas.sh — source this before configuring/building WebKit.
export PATH="/home/jonwise/hosttools/root/usr/bin:$PATH"
export LD_LIBRARY_PATH="/home/jonwise/hosttools/root/usr/lib/x86_64-linux-gnu${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export RUBYLIB="/home/jonwise/hosttools/root/usr/lib/ruby/3.2.0:/home/jonwise/hosttools/root/usr/lib/x86_64-linux-gnu/ruby/3.2.0"
