#!/bin/bash
# Stage the HOST-side build tools WPE WebKit needs that may not be installed (and that we cannot
# apt-get install without root): ruby and unifdef.
#
# WebKit's build runs ruby for its code generators (JavaScriptCore's offlineasm, the bindings
# generators) and unifdef for header post-processing. Both must be HOST (x86_64) binaries — they are
# build tools, not target code.
#
#   ./stage-hosttools-atlas.sh          # fetch + extract into $HOSTTOOLS (default ~/hosttools)
#   . ./hosttools-env.sh                # written by this script; puts them on PATH
#
# Unprivileged: `apt-get download` + `dpkg-deb -x` never touch the system. If your distro already has
# ruby and unifdef on PATH, you do not need this at all.
set -eu

HOSTTOOLS="${HOSTTOOLS:-$HOME/hosttools}"
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
mkdir -p "$HOSTTOOLS/debs" "$HOSTTOOLS/root"

need_ruby=1; need_unifdef=1
command -v ruby    >/dev/null 2>&1 && need_ruby=0
command -v unifdef >/dev/null 2>&1 && need_unifdef=0

pkgs=""
[ "$need_ruby" = 1 ]    && pkgs="$pkgs ruby3.2 libruby3.2"
[ "$need_unifdef" = 1 ] && pkgs="$pkgs unifdef"

if [ -n "$pkgs" ]; then
  echo "== fetching host tools:$pkgs =="
  ( cd "$HOSTTOOLS/debs" && apt-get download $pkgs )
  for d in "$HOSTTOOLS"/debs/*.deb; do dpkg-deb -x "$d" "$HOSTTOOLS/root"; done
  # Debian/Ubuntu ship the interpreter as ruby3.2; WebKit's generators invoke plain `ruby`.
  if [ -x "$HOSTTOOLS/root/usr/bin/ruby3.2" ] && [ ! -e "$HOSTTOOLS/root/usr/bin/ruby" ]; then
    ln -sf ruby3.2 "$HOSTTOOLS/root/usr/bin/ruby"
  fi
else
  echo "== host already has ruby + unifdef; nothing to fetch =="
fi

# An extracted (not installed) ruby finds neither its shared lib nor its stdlib without help.
cat > "$SCRIPT_DIR/hosttools-env.sh" <<EOF
# Generated by stage-hosttools-atlas.sh — source this before configuring/building WebKit.
export PATH="$HOSTTOOLS/root/usr/bin:\$PATH"
export LD_LIBRARY_PATH="$HOSTTOOLS/root/usr/lib/x86_64-linux-gnu\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
export RUBYLIB="$HOSTTOOLS/root/usr/lib/ruby/3.2.0:$HOSTTOOLS/root/usr/lib/x86_64-linux-gnu/ruby/3.2.0"
EOF

# shellcheck disable=SC1090
. "$SCRIPT_DIR/hosttools-env.sh"
echo "== verifying =="
ruby --version
ruby -e 'require "digest"; require "fileutils"; require "optparse"; require "stringio"; require "json"; puts "   ruby stdlib OK"'
unifdef -V 2>&1 | head -1
echo "== host tools ready; source $SCRIPT_DIR/hosttools-env.sh =="
